services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - FRONTEND_ORIGIN=http://localhost:3001
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:3000
    depends_on:
      - backend
